services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_NAME: advanced_wasel_palestine
